repos:
    git@gitlab.com:nikolay.r.borisov/webham.git:
        server_type: gitlab
        secret_token: fsdfsdf34234
        branch: refs/heads/master
        callbacks:
          -
            callback: \Webham\Devops\WebhookReceiverWorker\Plugin\PullPlugin::execute
            arguments: { branch: master, dir: '/etc/hosts' }
          -
            callback: \Webham\Devops\WebhookReceiverWorker\Plugin\PullPlugin::execute
            arguments: { branch: master, dir: '/etc/hosts' }
